### ISSUE TITLE
Feature request: 将目录下的所有 .md 文件格式化

### ISSUE THREAD

**Issue by jeremy-feng** [zhuozhiyongde/Match-Bracket-And-Pangu-Format#1]
感谢大佬开发的工具！

目前的脚本好像只能将某个目录下的 .md 文件格式化，我想递归地格式化某个目录下的所有 .md 文件（包括子目录、孙子目录等等下面的 .md 文件），希望可以加一个参数  `-r` 来实现。

**Comment by zhuozhiyongde** [comment]
源代码147~156行：
```python
    if len(sys.argv) == 2:
        if sys.argv[1].endswith('.md'):
            format_file(sys.argv[1])
        elif os.path.isdir(sys.argv[1]):
            md_files = [
                file for file in os.listdir(sys.argv[1])
                if file.endswith('.md')
            ]
            for file in md_files:
                format_file(f'{sys.argv[1]}/{file}')
```
我对输入参数是[做了判断的](https://github.com/zhuozhiyongde/Match-Bracket-And-Pangu-Format#other)。当前也支持遍历某一目录，如第二条命令会遍历Typora当前目录下的所有markdown文件（但不会递归遍历子目录）。

**Comment by jeremy-feng** [comment]
> 源代码147~156行：
> 
> ```python
>     if len(sys.argv) == 2:
>         if sys.argv[1].endswith('.md'):
>             format_file(sys.argv[1])
>         elif os.path.isdir(sys.argv[1]):
>             md_files = [
>                 file for file in os.listdir(sys.argv[1])
>                 if file.endswith('.md')
>             ]
>             for file in md_files:
>                 format_file(f'{sys.argv[1]}/{file}')
> ```
> 
> 我对输入参数是[做了判断的](https://github.com/zhuozhiyongde/Match-Bracket-And-Pangu-Format#other)。当前也支持遍历某一目录，如第二条命令会遍历Typora当前目录下的所有markdown文件（但不会递归遍历子目录）。

可以添加对“递归遍历子目录”的支持嘛？用参数 `-r` 代表递归子目录。有时候文件放在很深的目录中 😢

**Comment by zhuozhiyongde** [comment]
已添加此功能。

**Comment by zhuozhiyongde** [comment]
还有，其实我不建议你递归操作一个很大的目录，原因是这个操作目前并不支持撤销，如果操作出了问题（比如我的匹配写错了什么的），找回原有文本是不可能的。

**Comment by jeremy-feng** [comment]
太酷了！感谢你！
